accessing
checkResponse

	^ '<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:oc="http://owncloud.org/ns">
    <d:response>
        <d:href>/remote.php/dav/calendars/josafat-mattias.burm/swt_shared_by_hendrik.patzlaff/111111111111.ics</d:href>
        <d:propstat>
            <d:prop>
                <d:getetag>&quot;0b56fcc3c5000349bea1c7217c08c447&quot;</d:getetag>
            </d:prop>
            <d:status>HTTP/1.1 200 OK</d:status>
        </d:propstat>
    </d:response>
    <d:response>
        <d:href>/remote.php/dav/calendars/josafat-mattias.burm/swt_shared_by_hendrik.patzlaff/132456-34365</d:href>
        <d:propstat>
            <d:prop>
                <d:getetag>&quot;b04480a18c5a46543755830c11fe4e45&quot;</d:getetag>
            </d:prop>
            <d:status>HTTP/1.1 200 OK</d:status>
        </d:propstat>
    </d:response>
    <d:response>
        <d:href>/remote.php/dav/calendars/josafat-mattias.burm/swt_shared_by_hendrik.patzlaff/ownCloud-CQZQSONRVG6ER091V22SE.ics</d:href>
        <d:propstat>
            <d:prop>
                <d:getetag>&quot;9c15ecbc2762bb0321321d4ae33afbf4&quot;</d:getetag>
            </d:prop>
            <d:status>HTTP/1.1 200 OK</d:status>
        </d:propstat>
    </d:response>
    <d:response>
        <d:href>/remote.php/dav/calendars/josafat-mattias.burm/swt_shared_by_hendrik.patzlaff/ownCloud-GP5UKL2BRQSB88S4TJA1UI.ics</d:href>
        <d:propstat>
            <d:prop>
                <d:getetag>&quot;db57d9aaad4f8e7afab35382a60aef26&quot;</d:getetag>
            </d:prop>
            <d:status>HTTP/1.1 200 OK</d:status>
        </d:propstat>
    </d:response>
    <d:response>
        <d:href>/remote.php/dav/calendars/josafat-mattias.burm/swt_shared_by_hendrik.patzlaff/ownCloud-UVUC9KB5TLFK07PFN1BPZS.ics</d:href>
        <d:propstat>
            <d:prop>
                <d:getetag>&quot;1f326a16638a80f642005ac8678429ce&quot;</d:getetag>
            </d:prop>
            <d:status>HTTP/1.1 200 OK</d:status>
        </d:propstat>
    </d:response>
    <d:response>
        <d:href>/remote.php/dav/calendars/josafat-mattias.burm/swt_shared_by_hendrik.patzlaff/ownCloud-VD8WA8MYXUBMTLYKDG8UNH.ics</d:href>
        <d:propstat>
            <d:prop>
                <d:getetag>&quot;268c90404df41fd43eb8146607904dcf&quot;</d:getetag>
            </d:prop>
            <d:status>HTTP/1.1 200 OK</d:status>
        </d:propstat>
    </d:response>
</d:multistatus>'